name             'opsworks-elasticsearch-custom'
maintainer       'Joseph Chen'
maintainer_email 'joseph.chen@gmail.com'
license          'All rights reserved'
description      'Installs/Configures opsworks-elasticsearch-custom'
long_description 'Installs/Configures opsworks-elasticsearch-custom'
version          '0.1.0'
